Tue Nov 28 15:40:24 PST 2017

Duncan and I were talking about the code analysis, which is something I
need to get on. I'd like to do this in a literate programming style.

## Optimization

Consider execution of code as an optimization problem. The semantics of the
language are the constraints. We want to perform the same calculations,
only faster.

Suppose we're deciding whether to execute `lapply(x, f)` in serial
or in parallel via `parallel::mclapply(x, f)`. To make this decision
generally we need to know several parameters based on the code running on
that system:

(Units are seconds and bytes)

```{R}


p = list()

# How long does it take to execute f(x[i])?
# Assume this doesn't depend on x[i]
p$one_func_time = 1e-6

# How large is f(x[i])?
p$one_func_memory = 48

# How many elements in x?
p$n = length(x)

```

We also need to know something about that system:

```{R}

# How long does it take to call lapply / mclapply with no args?
mclapply_overhead_time = 5e-3
lapply_overhead_time = 2e-6

# What is the data transfer rate between processes?
# Units bytes / second
transfer_rate = 400e6

# How many parallel processors are available?
nprocs = 2

```

Now we can estimate the time required for serial and parallel executions:

```{R}

sertime = lapply_overhead_time + p$one_func_time * p$n

partime = mclapply_overhead_time + 
    p$one_func_time * ceiling(p$n / nprocs) +
    p$one_func_memory * p$n / transfer_rate

```

## Example

To make this concrete and validate the model I'll take an example of a
function I used recently. 


```{R}


```


