Mon Apr 23 09:15:19 PDT 2018

Working off this commit in rstatic:

```
commit d89d7572f8a375c97ecc5bfc59b40db8cf5d09f9
Author: Nick Ulle <nick.ulle@gmail.com>
Date:   Mon Apr 23 09:11:16 2018 -0700

    WIP: More fixes for data frames IR.
```

Does this split up sub expressions as we discussed?

Doesn't look like it.

```{R}

e = quote_blocks({
    x = rnorm(10)
    y = f(g(x, x2, h(x3)), x4, f5(x5))
}, ssa = FALSE)

e = as.data.frame(e)

```


I'm interested in identifying parallelism in for loops. This mean finding
read after write dependency, since this means they can't be parallelized.
`CodeAnalysis/explorations/loop_to_apply` has some existing work here.
Here's some examples from there:

```{R}

library(rstatic)

forloop = quote_blocks(
    for(i in seq_along(x)) {
        ans[i] = f(x[i])
    }
, ssa = FALSE)

f = as.data.frame(forloop)

# So the labels refer to the subexpressions to execute
f[1, 1][[1]]$body

f[3, 1][[1]]$read

f[3, 1][[1]]$write

```

# Data dependency

SSA should help identifying these cases.

## RAW Read After Write

Here's an example of one with true dependence, ie. not parallelizable:

```{R}

estimate = 10
for(i in 1:n) {
   estimate = update(estimate)
}

```

## WAW Write After Write

```{R}
for(i in 1:n) {
   tmp = f(i)
   ans[i] = tmp
   tmp = 20
}
```

Basic heuristic: If the LHS of the assignment, say `ans[i]`, is never used
on the RHS, then we should be able to parallelize the loop. Probably most
cases where we can make it parallel are when the code uses an index from
the loop.

The following is a certain "anti idiom" for growing a vector in R. The
problem is a lack of preallocation. If we apply the basic heuristic above
then we can't show that this loop is parallel, when in fact it's the same
as the most basic `ans = sapply(f, x)`.

```{R}
ans = numeric()
for(i in 1:n) {
    tmp = f(x[i])
    ans = c(ans, tmp)
}
```

Since it's an "anti idiom" maybe we can wait on handling it. Instead we
could handle this:

ans = numeric()
for(i in 1:n) {
    tmp = f(x[i])
    ans[i] = tmp
}


